name: Go

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
    
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0

    # Sonar cloud scan for TDBackend project
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.SQGH_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    # GoSec security scanner
    - name: Run Gosec Security Scanner
      uses: securego/gosec@master
      with:
        args: ./...

    # Get Project dependencies
    - name: Get dependencies
      run: |
       if [ -f go.mod ]; then
            go mod tidy
            go mod vendor
        fi

    - name: Build
      run: go build -v .

    - name: Test
      run: go test -v .
